name: free3
services:
  challenge:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FLAG: "flag{***REDACTED***}"
    container_name: free3
    environment:
      - JAIL_TIME=300
      - JAIL_CONNS_PER_IP=3
      - JAIL_POW=0
    ports:
      - "8215:5000"
    privileged: true
    restart: always
