services:
  secret-notes:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src/chal_orig:/home/secret_notes/chal:ro
      - ./src/run.sh:/home/secret_notes/run.sh:ro
      - ./flag:/flag:ro
    ports:
      - 12387:12387
    stop_grace_period: 1s
